; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare_rp2040_zero]
platform = raspberrypi
board = waveshare_rp2040_zero
framework = arduino

lib_deps =
  adafruit/Adafruit MCP2515 @ ^0.2.1
  adafruit/Adafruit PWM Servo Driver Library
  adafruit/Adafruit NeoPixel

build_src_filter =
  +<main.cpp>

[env:waveshare_rp2040_zero_link]
platform = raspberrypi
board = waveshare_rp2040_zero
framework = arduino

lib_deps =
  adafruit/Adafruit NeoPixel

build_src_filter =
  +<minimal_link.cpp>

[env:i2c_sweep]
platform = raspberrypi
board = waveshare_rp2040_zero
framework = arduino

build_src_filter =
  +<i2c_sweep.cpp>

[env:can_test]
platform = raspberrypi
board = waveshare_rp2040_zero
framework = arduino
board_build.variant = waveshare_rp2040_zero_can
board_build.variants_dir = variants

lib_deps =
  adafruit/Adafruit MCP2515 @ ^0.2.1

build_src_filter =
  +<can_test.cpp>


[platformio]
extra_configs = ~/.platformio/barrypi_base.ini

[env:can_test_alt_rp2040]
extends = barrypi_base
framework = arduino

build_flags =
  -DCAN_TEST_ALT_RP2040

lib_deps =
  adafruit/Adafruit MCP2515 @ ^0.2.1

build_src_filter =
  +<can_test.cpp>
